# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Charlotte and Joe 
description:      'Wedding 2015'
url:              http://charlotteandjoe2015.github.io/

author:
  name:           'Joe Smallman'
  url:            https://twitter.com/SmallJoeMan
